name: smart-wifi-attendance
services:
- name: backend
  source_dir: /backend
  github:
    repo: Spoilersignals/PROJECTO
    branch: main
  dockerfile_path: backend/Dockerfile
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 5000
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"
  - key: MONGODB_URI
    value: ${MONGODB_URI}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: JWT_REFRESH_SECRET
    value: ${JWT_REFRESH_SECRET}
  - key: JWT_EXPIRES_IN
    value: 1h
  - key: JWT_REFRESH_EXPIRES_IN
    value: 7d
  - key: CORS_ORIGIN
    value: ${APP_URL}

- name: frontend
  source_dir: /frontend
  github:
    repo: Spoilersignals/PROJECTO
    branch: main
  dockerfile_path: frontend/Dockerfile
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 3000
  envs:
  - key: REACT_APP_API_URL
    value: ${backend.PUBLIC_URL}/api
  - key: GENERATE_SOURCEMAP
    value: "false"
